export const VALID = [
  "username",
  "username123",
  "username_123",
  "suzanadeov",
  "nicolas",
  "renatobmps",
  "renatobmpsilva",
  "monicabdolv",
  "steelfox",
  "natalia",
  "rodrigobmps",
  "johnwick",
  "gabii03",
  "123",
  "diego_amps",
  "denilson",
  "renato",
  "brunafurlan",
  "fredson",
  "anthonyfurlan",
]

export const INVALID = [
  { text: "", expect: "" },
  { text: "user name", expect: "user_name" },
  { text: "user     name", expect: "user_name" },
  { text: "name@example.com", expect: "name@example.com" },
  { text: "USERNAME", expect: "username" },
  { text: "Simone Martins Pinheiro", expect: "simone_martins_pinheiro" },
  { text: "Fernanda", expect: "fernanda" },
  { text: "Gabriel Grandão", expect: "gabriel_grandao" },
  { text: "Família ", expect: "familia" },
  { text: "Walki", expect: "walki" },
  { text: "Yutaro", expect: "yutaro" },
  { text: "Aribe013", expect: "aribe013" },
  { text: "Sah ", expect: "sah" },
  { text: "denilsonmpinheiro@hotmail.com", expect: "denilsonmpinheiro@hotmail.com" },
  { text: "Danila1", expect: "danila1" },
  { text: "RENATO  BRANDÃO", expect: "renato_brandao" }
]