FROM node:22-slim AS builder 
LABEL maintainer="Renato Brandão"

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . ./

FROM node:22-alpine3.20

ARG NODE_ENV=development

WORKDIR /app

COPY --from=builder /app/ ./

CMD [ "npm", "run", "dev"]
