import { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import '../common/styles/global.css';
import Layout from '@/common/components/layout';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const PageLayout = ({ children }: PropsWithChildren) => (
  <Layout.ClientLayout>{children}</Layout.ClientLayout>
)

export default PageLayout