services:
  database:
    image: "postgres:17.0-alpine3.20"
    env_file:
      - .env
    ports:
      - "5432:5432"
  backend:
    container_name: "hangman_backend"
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000