services:
  app:
    container_name: "hangman"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: "postgres:16.1-alpine3.19"
    env_file:
      - .env
    ports:
      - "5432:5432"
