name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        env:
          DB_DIALECT_SECRET: ${{ secrets.DB_DIALECT }}
        run: |
          docker build . \
            --build-arg DB_DIALECT="$DB_DIALECT_SECRET" \
            --file Dockerfile \
            --tag hangman:$(date +%s)
